name: Update Date in README

on:
  schedule:
    - cron: '0 0 * * *' # Tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Lancer le script de mise à jour
        run: python update_date.py

      - name: Commit et Push les changements
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --staged --quiet; then
            echo "Pas de changements détectés."
          else
            git commit -m "Auto-update date: $(date +'%d/%m/%Y')"
            git push
          fi
